language: Fortran
before_install:
  - sudo apt-get -qq install gfortran ruby1.9.3
  - sudo gem install erb fort
script:
  - cd src && rake1.9.3 test
env:
  - MY_ERB=erb1.9.3
  - MY_GFORTRAN=gfortran-4.7
